# ECU Configuration - Electric Power Steering
# This file contains the ECU-specific configuration including addresses and UDS services

ecu:
  name: "Steering_EPS"
  description: "Electric Power Steering"
  target_address: 0x05  # Match doip_tester_yaml logical address
  functional_address: 0x0000  # Match doip_tester_yaml functional address
  tester_addresses:
    - 0x0E80  # Match doip_tester_yaml tester address
    - 0x0E00  # Primary tester
    - 0x0E01  # Backup tester
    - 0x0E02  # Diagnostic tool
  
  # ECU-specific settings
  settings:
    enable_routine_activation: true
    enable_uds_services: true
    session_timeout: 30
    max_concurrent_sessions: 2
    
  # Routine Activation Configuration
  routine_activation:
    active_type: 0x00  # default
    reserved_by_iso: 0x00000000
    reserved_by_manufacturer: 0x00000000
    
  # UDS Services Configuration - References to service files
  uds_services:
    # Service files to load for this ECU
    service_files:
      - "config/generic/generic_uds_messages.yaml"  # Common services
      - "ecu_steering_services.yaml"                # Steering-specific services
    
    # Service categories (for backward compatibility)
    common_services:
      - "Read_VIN"
      - "Read_Vehicle_Type"
      - "Routine_calibration_start"
      - "Routine_calibration_stop"
      - "Routine_calibration_status"
      - "Diagnostic_Session_Control"
      - "Tester_Present"
      - "Security_Access"
    
    # ECU-specific services (only available for this ECU)
    specific_services:
      - "Steering_Angle_Read"
      - "Steering_Torque_Read"
      - "Steering_System_Status_Read"
      - "Steering_Diagnostic_Codes"
      - "Steering_Calibration_Reset"
      - "Steering_Motor_Test"
      - "Steering_Sensor_Test"
      - "Steering_System_Voltage_Read"
      - "Steering_Learning_Procedure"
      - "Steering_System_Reset"
