# ESP ECU Services Configuration
# Electronic Stability Program Control Unit

specific_services:
  ReadDTCInformation_StatusOfDTC:
    request: "0x1902"
    responses:
      - "0x5902"
    description: "Read DTC Information Status of DTC"
    supports_functional: true