# Transmission ECU Specific UDS Services
# This file contains UDS services specific to the Transmission Control Unit

specific_services:
  Transmission_Gear_Read:
    request: "0x220C0A"
    responses:
      - "0x620C0A01"  # 1st gear
      - "0x620C0A02"  # 2nd gear
      - "0x620C0A03"  # 3rd gear
      - "0x620C0A04"  # 4th gear
      - "0x620C0A05"  # 5th gear
      - "0x620C0A06"  # 6th gear
      - "0x620C0A00"  # Neutral
      - "0x620C0AFF"  # Reverse
    description: "Read current gear"
    supports_functional: false  # Physical addressing only
    
  Transmission_Temperature_Read:
    request: "0x220C0C"
    responses:
      - "0x620C0C70"  # 70°C
      - "0x620C0C80"  # 80°C
      - "0x620C0C90"  # 90°C
    description: "Read transmission temperature"
    supports_functional: false  # Physical addressing only
    
  Transmission_Fluid_Level_Read:
    request: "0x220C0D"
    responses:
      - "0x620C0D80"  # 80% fluid level
      - "0x620C0D90"  # 90% fluid level
      - "0x620C0D70"  # 70% fluid level
    description: "Read transmission fluid level"
    supports_functional: false  # Physical addressing only
    
  Transmission_Shift_Control:
    request: "0x31020001"
    responses:
      - "0x71020001"  # Shift command accepted
      - "0x71020002"  # Shift command rejected
    description: "Transmission shift control"
    supports_functional: false  # Physical addressing only
    
  Transmission_Diagnostic_Codes:
    request: "0x1902"
    responses:
      - "0x5902"  # No DTCs
      - "0x5902P0700"  # P0700 - Transmission control system
      - "0x5902P0701"  # P0701 - Transmission control system range/performance
      - "0x5902P0702"  # P0702 - Transmission control system electrical
    description: "Read transmission diagnostic trouble codes"
    supports_functional: true  # Supports both physical and functional addressing
    
  Transmission_Adaptation_Reset:
    request: "0x31030001"
    responses:
      - "0x71030001"  # Adaptation reset successful
    description: "Reset transmission adaptations"
    supports_functional: false  # Physical addressing only

  Transmission_Torque_Converter_Status:
    request: "0x220C0E"
    responses:
      - "0x620C0E00"  # Locked
      - "0x620C0E01"  # Unlocked
      - "0x620C0E02"  # Slipping
    description: "Read torque converter lock status"
    supports_functional: false  # Physical addressing only

  Transmission_Shift_Pressure_Read:
    request: "0x220C0F"
    responses:
      - "0x620C0F80"  # 80% pressure
      - "0x620C0F90"  # 90% pressure
      - "0x620C0F70"  # 70% pressure
    description: "Read transmission shift pressure"
    supports_functional: false  # Physical addressing only

  Transmission_Clutch_Status:
    request: "0x220C10"
    responses:
      - "0x620C1000"  # Disengaged
      - "0x620C1001"  # Engaged
      - "0x620C1002"  # Slipping
    description: "Read clutch engagement status"
    supports_functional: false  # Physical addressing only

  Transmission_Learning_Status:
    request: "0x220C11"
    responses:
      - "0x620C1100"  # Learning complete
      - "0x620C1101"  # Learning in progress
      - "0x620C1102"  # Learning required
    description: "Read transmission learning status"
    supports_functional: false  # Physical addressing only

  Transmission_Valve_Body_Test:
    request: "0x31040001"
    responses:
      - "0x71040001"  # Test passed
      - "0x71040002"  # Test failed
    description: "Transmission valve body test"
    supports_functional: false  # Physical addressing only

  Transmission_Pump_Test:
    request: "0x31050001"
    responses:
      - "0x71050001"  # Test passed
      - "0x71050002"  # Test failed
    description: "Transmission pump test"
    supports_functional: false  # Physical addressing only

  Transmission_Calibration_Reset:
    request: "0x31060001"
    responses:
      - "0x71060001"  # Calibration reset successful
    description: "Reset transmission calibration"
    supports_functional: false  # Physical addressing only
