# Gateway ECU Specific UDS Services
# This file contains UDS services specific to the Gateway ECU

specific_services:
  Gateway_Network_Status_Read:
    request: "0x22100E"
    responses:
      - "0x62100E00"  # Network OK
      - "0x62100E01"  # Network warning
      - "0x62100E02"  # Network error
    description: "Read gateway network status"
    supports_functional: false  # Physical addressing only
    
  Gateway_ECU_List_Read:
    request: "0x22100F"
    responses:
      - "0x62100F0102030405060708090A0B0C0D0E0F"  # List of connected ECUs
    description: "Read list of connected ECUs"
    supports_functional: false  # Physical addressing only
    
  Gateway_Diagnostic_Codes:
    request: "0x1902"
    responses:
      - "0x5902"  # No DTCs
      - "0x5902C0000"  # C0000 - No fault
      - "0x5902C0001"  # C0001 - Network fault
      - "0x5902C0002"  # C0002 - Communication fault
      - "0x5902C0003"  # C0003 - Gateway fault
    description: "Read gateway diagnostic trouble codes"
    supports_functional: true  # Supports both physical and functional addressing
    
  Gateway_Calibration_Reset:
    request: "0x31060001"
    responses:
      - "0x71060001"  # Calibration reset successful
    description: "Reset gateway calibration"
    supports_functional: false  # Physical addressing only

  Gateway_Network_Test:
    request: "0x31040001"
    responses:
      - "0x71040001"  # Test passed
      - "0x71040002"  # Test failed
    description: "Gateway network test"
    supports_functional: false  # Physical addressing only

  Gateway_Communication_Test:
    request: "0x31050001"
    responses:
      - "0x71050001"  # Test passed
      - "0x71050002"  # Test failed
    description: "Gateway communication test"
    supports_functional: false  # Physical addressing only

  Gateway_System_Voltage_Read:
    request: "0x221010"
    responses:
      - "0x6210100C"  # 12V
      - "0x62101014"  # 14V
      - "0x62101016"  # 16V
    description: "Read gateway system voltage"
    supports_functional: false  # Physical addressing only

  Gateway_Learning_Procedure:
    request: "0x31070001"
    responses:
      - "0x71070001"  # Learning procedure started
      - "0x71070002"  # Learning procedure complete
      - "0x71070003"  # Learning procedure failed
    description: "Start gateway learning procedure"
    supports_functional: false  # Physical addressing only

  Gateway_System_Reset:
    request: "0x31090001"
    responses:
      - "0x71090001"  # System reset successful
    description: "Reset gateway system"
    supports_functional: false  # Physical addressing only
