# ABS ECU Specific UDS Services
# This file contains UDS services specific to the Anti-lock Braking System Control Unit

specific_services:
  ABS_Wheel_Speed_Read:
    request: "0x220C0B"
    responses:
      - "0x620C0B0000"  # 0 km/h
      - "0x620C0B0032"  # 50 km/h
      - "0x620C0B0064"  # 100 km/h
      - "0x620C0B0096"  # 150 km/h
    description: "Read wheel speed"
    supports_functional: false  # Physical addressing only
    
  ABS_System_Status_Read:
    request: "0x220C0E"
    responses:
      - "0x620C0E00"  # System OK
      - "0x620C0E01"  # System warning
      - "0x620C0E02"  # System error
    description: "Read ABS system status"
    supports_functional: false  # Physical addressing only
    
  ABS_Valve_Test:
    request: "0x31040001"
    responses:
      - "0x71040001"  # Test passed
      - "0x71040002"  # Test failed
    description: "ABS valve test"
    supports_functional: false  # Physical addressing only
    
  ABS_Pump_Test:
    request: "0x31050001"
    responses:
      - "0x71050001"  # Test passed
      - "0x71050002"  # Test failed
    description: "ABS pump test"
    supports_functional: false  # Physical addressing only
    
  ABS_Diagnostic_Codes:
    request: "0x1902"
    responses:
      - "0x5902"  # No DTCs
      - "0x5902C0000"  # C0000 - No fault
      - "0x5902C0001"  # C0001 - Left front wheel speed sensor
      - "0x5902C0002"  # C0002 - Right front wheel speed sensor
      - "0x5902C0003"  # C0003 - Left rear wheel speed sensor
      - "0x5902C0004"  # C0004 - Right rear wheel speed sensor
    description: "Read ABS diagnostic trouble codes"
    supports_functional: true  # Supports both physical and functional addressing
    
  ABS_Calibration_Reset:
    request: "0x31060001"
    responses:
      - "0x71060001"  # Calibration reset successful
    description: "Reset ABS calibration"
    supports_functional: false  # Physical addressing only

  ABS_Wheel_Speed_Sensor_Test:
    request: "0x220C0C"
    responses:
      - "0x620C0C00"  # All sensors OK
      - "0x620C0C01"  # Front left sensor fault
      - "0x620C0C02"  # Front right sensor fault
      - "0x620C0C03"  # Rear left sensor fault
      - "0x620C0C04"  # Rear right sensor fault
    description: "Test ABS wheel speed sensors"
    supports_functional: false  # Physical addressing only

  ABS_Hydraulic_Unit_Test:
    request: "0x220C0D"
    responses:
      - "0x620C0D00"  # Hydraulic unit OK
      - "0x620C0D01"  # Hydraulic unit fault
    description: "Test ABS hydraulic unit"
    supports_functional: false  # Physical addressing only

  ABS_ECU_Temperature_Read:
    request: "0x220C0F"
    responses:
      - "0x620C0F40"  # 40°C
      - "0x620C0F50"  # 50°C
      - "0x620C0F60"  # 60°C
    description: "Read ABS ECU temperature"
    supports_functional: false  # Physical addressing only

  ABS_Brake_Pressure_Read:
    request: "0x220C10"
    responses:
      - "0x620C1000"  # 0 bar
      - "0x620C1080"  # 80 bar
      - "0x620C10FF"  # 255 bar (max)
    description: "Read brake pressure"
    supports_functional: false  # Physical addressing only

  ABS_System_Voltage_Read:
    request: "0x220C11"
    responses:
      - "0x620C110C"  # 12V
      - "0x620C1114"  # 14V
      - "0x620C1116"  # 16V
    description: "Read ABS system voltage"
    supports_functional: false  # Physical addressing only

  ABS_Learning_Procedure:
    request: "0x31070001"
    responses:
      - "0x71070001"  # Learning procedure started
      - "0x71070002"  # Learning procedure complete
      - "0x71070003"  # Learning procedure failed
    description: "Start ABS learning procedure"
    supports_functional: false  # Physical addressing only

  ABS_Valve_Calibration:
    request: "0x31080001"
    responses:
      - "0x71080001"  # Calibration successful
      - "0x71080002"  # Calibration failed
    description: "Calibrate ABS valves"
    supports_functional: false  # Physical addressing only

  ABS_System_Reset:
    request: "0x31090001"
    responses:
      - "0x71090001"  # System reset successful
    description: "Reset ABS system"
    supports_functional: false  # Physical addressing only
