# DoIP Server Configuration
# This file contains all configurable parameters for the DoIP server

# Server Configuration
server:
  host: "0.0.0.0"
  port: 13400
  max_connections: 5
  timeout: 30

# Protocol Configuration
protocol:
  version: 0x02
  inverse_version: 0xFD

# Address Configuration
addresses:
  # Source addresses that are allowed to send requests
  allowed_sources:
    - 0x0E00  # Tester
    - 0x0E01  # Alternative tester
    - 0x0E02  # Another tester
  
  # Target addresses this server represents
  target_addresses:
    - 0x1000  # ECU 1
    - 0x1001  # ECU 2
    - 0x1002  # ECU 3
  
  # Default source address for responses (this server)
  default_source: 0x1000

# Routine Activation Configuration
routine_activation:
  active_type: 0x00 #default
  reserved_by_iso: 0x00000000
  reserved_by_manufacturer: 0x00000000

# UDS Services Configuration
uds_services:
  
  Read_VIN:
    request: "0x22F190"
    responses:  
      - "0x62F1901020011223344556677889AABB"
      - "0x62F1901020011223344556677889BBCC"
  Read_Vehicle_Type:
    request: "0x22F191"
    responses:  
      - "0x62F1911020011223344556677889AABB"
      - "0x62F1911020011223344556677889BBCC"
  Routine_calibration_start:
    request: "0x31010202"
    responses:  
      - "0x71010202"
  Routine_calibration_stop:
    request: "0x31020202"
    responses:  
      - "0x71020202"
  Routine_calibration_status:
    request: "0x31030202"
    responses:  
      - "0x7103020210"
      - "0x7103020212"

# Response Codes
response_codes:
  routine_activation:
    0x10: "Routine started successfully"
    0x22: "Conditions not correct"
    0x31: "Incorrect routine identifier"
    0x33: "Security access denied"
  
  uds:
    0x10: "General reject"
    0x12: "Sub-function not supported"
    0x13: "Incorrect message length or invalid format"
    0x22: "Conditions not correct"
    0x24: "Request sequence error"
    0x31: "Request out of range"
    0x33: "Security access denied"
    0x35: "Invalid key"
    0x36: "Exceeded number of attempts"
    0x37: "Required time delay not expired"
    0x70: "Upload download not accepted"
    0x71: "Transfer data suspended"
    0x72: "General programming failure"
    0x73: "Wrong block sequence counter"
    0x78: "Request correctly received - response pending"
    0x7E: "Sub-function not supported in active session"
    0x7F: "Service not supported in active session"

# Logging Configuration
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR, CRITICAL
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "doip_server.log"
  console: true

# Security Configuration
security:
  # Enable/disable security features
  enabled: false
  
  # Allowed source addresses (if security is enabled)
  allowed_sources_strict: false
  
  # Authentication required for sensitive operations
  require_auth_for:
    - "routine_activation"
    - "uds_write_operations"
