# ECU Configuration - ABS Control Unit
# This file contains the ECU-specific configuration including addresses and UDS services

ecu:
  name: "ABS_ECU"
  description: "Anti-lock Braking System Control Unit"
  target_address: 0x1002
  functional_address: 0x1FFF  # Functional address for broadcast diagnostics
  tester_addresses:
    - 0x0E00  # Primary tester
    - 0x0E01  # Backup tester
    - 0x0E02  # Diagnostic tool
  
  # ECU-specific settings
  settings:
    enable_routine_activation: true
    enable_uds_services: true
    session_timeout: 30
    max_concurrent_sessions: 2
    
  # Routine Activation Configuration
  routine_activation:
    active_type: 0x00  # default
    reserved_by_iso: 0x00000000
    reserved_by_manufacturer: 0x00000000
    
  # UDS Services Configuration - References to service files
  uds_services:
    # Service files to load for this ECU
    service_files:
      - "config/generic_uds_messages.yaml"  # Common services
      - "config/ecu_abs_services.yaml"      # ABS-specific services
    
    # Service categories (for backward compatibility)
    common_services:
      - "Read_VIN"
      - "Read_Vehicle_Type"
      - "Routine_calibration_start"
      - "Routine_calibration_stop"
      - "Routine_calibration_status"
      - "Diagnostic_Session_Control"
      - "Tester_Present"
      - "Security_Access"
    
    # ECU-specific services (only available for this ECU)
    specific_services:
      - "ABS_Wheel_Speed_Read"
      - "ABS_System_Status_Read"
      - "ABS_Valve_Test"
      - "ABS_Pump_Test"
      - "ABS_Diagnostic_Codes"
      - "ABS_Calibration_Reset"
      - "ABS_Wheel_Speed_Sensor_Test"
      - "ABS_Hydraulic_Unit_Test"
      - "ABS_ECU_Temperature_Read"
      - "ABS_Brake_Pressure_Read"
      - "ABS_System_Voltage_Read"
      - "ABS_Learning_Procedure"
      - "ABS_Valve_Calibration"
      - "ABS_System_Reset"
