# ECU Configuration - Engine Control Unit
# This file contains the ECU-specific configuration including addresses and UDS services

ecu:
  name: "Engine_ECU"
  description: "Engine Control Unit"
  target_address: 0x1000
  functional_address: 0x1FFF  # Functional address for broadcast diagnostics
  tester_addresses:
    - 0x0E00  # Primary tester
    - 0x0E01  # Backup tester
    - 0x0E02  # Diagnostic tool
  
  # ECU-specific settings
  settings:
    enable_routine_activation: true
    enable_uds_services: true
    session_timeout: 30
    max_concurrent_sessions: 3
    
  # Routine Activation Configuration
  routine_activation:
    active_type: 0x00  # default
    reserved_by_iso: 0x00000000
    reserved_by_manufacturer: 0x00000000
    
  # UDS Services Reference - Points to services configuration
  uds_services:
    # Common services shared across all ECUs
    common_services:
      - "Read_VIN"
      - "Read_Vehicle_Type"
      - "Routine_calibration_start"
      - "Routine_calibration_stop"
      - "Routine_calibration_status"
      - "Diagnostic_Session_Control"
      - "Tester_Present"
      - "Security_Access"
    
    # ECU-specific services (only available for this ECU)
    specific_services:
      - "Engine_RPM_Read"
      - "Engine_Temperature_Read"
      - "Fuel_Level_Read"
      - "Engine_Start_Stop"
      - "Throttle_Position_Read"
      - "Engine_Diagnostic_Codes"
