# ECU Configuration - Transmission Control Unit
# This file contains the ECU-specific configuration including addresses and UDS services

ecu:
  name: "Transmission_ECU"
  description: "Transmission Control Unit"
  target_address: 0x1001
  functional_address: 0x1FFF  # Functional address for broadcast diagnostics
  tester_addresses:
    - 0x0E00  # Primary tester
    - 0x0E01  # Backup tester
    - 0x0E02  # Diagnostic tool
  
  # ECU-specific settings
  settings:
    enable_routine_activation: true
    enable_uds_services: true
    session_timeout: 30
    max_concurrent_sessions: 2
    
  # Routine Activation Configuration
  routine_activation:
    active_type: 0x00  # default
    reserved_by_iso: 0x00000000
    reserved_by_manufacturer: 0x00000000
    
  # UDS Services Configuration - References to service files
  uds_services:
    # Service files to load for this ECU
    service_files:
      - "config/generic_uds_messages.yaml"        # Common services
      - "config/ecu_transmission_services.yaml"   # Transmission-specific services
    
    # Service categories (for backward compatibility)
    common_services:
      - "Read_VIN"
      - "Read_Vehicle_Type"
      - "Routine_calibration_start"
      - "Routine_calibration_stop"
      - "Routine_calibration_status"
      - "Diagnostic_Session_Control"
      - "Tester_Present"
      - "Security_Access"
    
    # ECU-specific services (only available for this ECU)
    specific_services:
      - "Transmission_Gear_Read"
      - "Transmission_Temperature_Read"
      - "Transmission_Fluid_Level_Read"
      - "Transmission_Shift_Control"
      - "Transmission_Diagnostic_Codes"
      - "Transmission_Adaptation_Reset"
      - "Transmission_Torque_Converter_Status"
      - "Transmission_Shift_Pressure_Read"
      - "Transmission_Clutch_Status"
      - "Transmission_Learning_Status"
      - "Transmission_Valve_Body_Test"
      - "Transmission_Pump_Test"
      - "Transmission_Calibration_Reset"
