# Gateway Configuration - TCP/IP Network Settings
# This file contains the network configuration for a DoIP gateway

gateway:
  name: "Gateway1"
  description: "Primary DoIP Gateway"
  logical_address: 0x1000  # Gateway logical address
  
  # Vehicle Information
  vehicle:
    vin: "1HGBH41JXMN109186"  # Vehicle Identification Number
    eid: "123456789ABC"  # Entity ID (6 bytes hex)
    gid: "DEF012345678"  # Group ID (6 bytes hex)
  
  # TCP/IP Network Configuration
  network:
    host: "0.0.0.0"  # Listen on all interfaces
    port: 13400
    max_connections: 10
    timeout: 60
    keep_alive: true
    tcp_nodelay: true
    
  # Protocol Configuration
  protocol:
    version: 0x02
    inverse_version: 0xFD
    
  # Gateway-specific settings
  settings:
    enable_logging: true
    log_level: "INFO"
    enable_security: false
    allow_multiple_sessions: true
    
  # ECU References - List of ECU configuration files
  ecus:
    - "ecus/engine/ecu_engine.yaml"
    - "ecus/transmission/ecu_transmission.yaml" 
    - "ecus/abs/ecu_abs.yaml"
    
  # Response Codes Configuration
  response_codes:
    routine_activation:
      0x10: "Routine started successfully"
      0x22: "Conditions not correct"
      0x31: "Incorrect routine identifier"
      0x33: "Security access denied"
    
    uds:
      0x10: "General reject"
      0x12: "Sub-function not supported"
      0x13: "Incorrect message length or invalid format"
      0x22: "Conditions not correct"
      0x24: "Request sequence error"
      0x31: "Request out of range"
      0x33: "Security access denied"
      0x35: "Invalid key"
      0x36: "Exceeded number of attempts"
      0x37: "Required time delay not expired"
      0x70: "Upload download not accepted"
      0x71: "Transfer data suspended"
      0x72: "General programming failure"
      0x73: "Wrong block sequence counter"
      0x78: "Request correctly received - response pending"
      0x7E: "Sub-function not supported in active session"
      0x7F: "Service not supported in active session"

  # Power Mode Status Configuration
  power_mode_status:
    description: "Power mode status values for DoIP power mode response (payload type 0x0008)"
    current_status: 0x0001  # Current power mode status (2 bytes)
    available_statuses:
      0x0000: 
        name: "Power Off"
        description: "ECU is powered off"
      0x0001:
        name: "Power On"
        description: "ECU is powered on and ready"
      0x0002:
        name: "Power Standby"
        description: "ECU is in standby mode"
      0x0003:
        name: "Power Sleep"
        description: "ECU is in sleep mode"
      0x0004:
        name: "Power Wake"
        description: "ECU is waking up"
    response_cycling:
      enabled: false  # Enable cycling through different power mode statuses
      cycle_through: [0x0001, 0x0002, 0x0003]  # Statuses to cycle through

# Logging Configuration
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR, CRITICAL
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "doip_server.log"
  console: true
  max_file_size: "10MB"
  backup_count: 5

# Security Configuration
security:
  enabled: false
  allowed_sources_strict: false
  require_auth_for:
    - "routine_activation"
    - "uds_write_operations"
