# ECU Configuration - Engine Control Unit
# This file contains the ECU-specific configuration including addresses and UDS services

ecu:
  name: "Engine_ECM"
  description: "Engine Control Module"
  target_address: 0x01  # Match doip_tester_yaml logical address
  functional_address: 0x0000  # Match doip_tester_yaml functional address
  tester_addresses:
    - 0x0E80  # Match doip_tester_yaml tester address
    - 0x0E00  # Primary tester
    - 0x0E01  # Backup tester
    - 0x0E02  # Diagnostic tool
  
  # ECU-specific settings
  settings:
    enable_routine_activation: true
    enable_uds_services: true
    session_timeout: 30
    max_concurrent_sessions: 3
    
  # Routine Activation Configuration
  routine_activation:
    active_type: 0x00  # default
    reserved_by_iso: 0x00000000
    reserved_by_manufacturer: 0x00000000
    
  # UDS Services Configuration - References to service files
  uds_services:
    # Service files to load for this ECU
    service_files:
      - "config/generic/generic_uds_messages.yaml"  # Common services
      - "ecu_engine_services.yaml"                  # Engine-specific services
    
    # Service categories (for backward compatibility)
    common_services:
      - "Read_VIN"
      - "Read_Vehicle_Type"
      - "Routine_calibration_start"
      - "Routine_calibration_stop"
      - "Routine_calibration_status"
      - "Diagnostic_Session_Control"
      - "Tester_Present"
      - "Security_Access"
    
    # ECU-specific services (only available for this ECU)
    specific_services:
      - "Engine_RPM_Read"
      - "Engine_Temperature_Read"
      - "Fuel_Level_Read"
      - "Engine_Start_Stop"
      - "Throttle_Position_Read"
      - "Engine_Diagnostic_Codes"
      - "Engine_Load_Read"
      - "Intake_Air_Temperature_Read"
      - "Manifold_Absolute_Pressure_Read"
      - "Engine_Oil_Pressure_Read"
      - "Engine_Coolant_Level_Read"
      - "Engine_Adaptation_Reset"
      - "Engine_Calibration_Status"
